export const BIOMES = {
  BAMBOO_GROVE: {
    id: 'BAMBOO_GROVE',
    name: 'Verdant Bamboo Grove',
    baseHeight: 4,
    heightVariance: 6,
    fogColor: 0x0f2015,
    grassColor: 0x2d5a27,
    rockColor: 0x4a4f44,
    floraDensity: 0.8,
    bambooDensity: 0.7,
    bushLurkerChance: 0.35,
    ghostChance: 0.05,
    foodYield: ['wildBerries', 'shiitakeMushroom', 'forestHerb'],
    oreYield: ['ironOre', 'silverNugget']
  },
  MISTY_GRAVEYARD: {
    id: 'MISTY_GRAVEYARD',
    name: 'Cursed Misty Ruins',
    baseHeight: 2,
    heightVariance: 8,
    fogColor: 0x08101a,
    grassColor: 0x1c2b2b,
    rockColor: 0x2f3640,
    floraDensity: 0.3,
    bambooDensity: 0.1,
    bushLurkerChance: 0.15,
    ghostChance: 0.6,
    foodYield: ['spiritLotus', 'shadowFungus'],
    oreYield: ['silverNugget', 'ancientStone']
  },
  ROCKY_PEAKS: {
    id: 'ROCKY_PEAKS',
    name: 'Highland Ore Crags',
    baseHeight: 12,
    heightVariance: 18,
    fogColor: 0x141824,
    grassColor: 0x3d4a36,
    rockColor: 0x5a5d64,
    floraDensity: 0.2,
    bambooDensity: 0.05,
    bushLurkerChance: 0.2,
    ghostChance: 0.1,
    roninChance: 0.45,
    foodYield: ['mountainRoot'],
    oreYield: ['goldNugget', 'ironOre', 'diamondOre']
  },
  SACRED_SANCTUARY: {
    id: 'SACRED_SANCTUARY',
    name: 'Sacred Blossom Shrine',
    baseHeight: 6,
    heightVariance: 4,
    fogColor: 0x1f1624,
    grassColor: 0x3d6635,
    rockColor: 0x5e564d,
    floraDensity: 0.9,
    bambooDensity: 0.2,
    sakuraDensity: 0.6,
    bushLurkerChance: 0.0,
    ghostChance: 0.0,
    isSafeZone: true,
    foodYield: ['healingHerb', 'sakuraTeaLeaf', 'wildPeach'],
    oreYield: ['goldNugget', 'silverNugget']
  }
};
